name: KTLint Validation

on:
  push:
    branches: [release/**]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: develop

      - uses: actions/checkout@master

      - name: Calculate release version
        uses: actions/github-script@v3
        id: release_version
        with:
          github-token: ${{ github.token }}
          script: |
            const opts = await github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "develop",
            });
            const base = opts.data.commit.sha
            const head = context.payload.after
            const commits = await github.repos
              .compareCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                base,
                head,
              })
            const version = context.payload.ref.split('/')[3] + "." + commits.data.commits.length
            core.setOutput("version", version);

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.release_version.outputs.version }}",
              sha: context.sha
            })

      - name: Generate release notes
        uses: ./
        id: notes
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          task_service: "https://github.com/RodrigoAmaroEng/release-notes-action/issues/"
          release_version: ${{ steps.release_version.outputs.version }}

      - name: Create a Release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.release_version.outputs.version }}
          release_name: ${{ steps.release_version.outputs.version }}
          body: ${{ steps.notes.outputs.notes }}
