name: KTLint Validation

on:
  push:
    branches: [release/**]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: develop

      - uses: actions/checkout@master

      - name: Calculate release version
        shell: bash
        id: release_version
        run: |
          commits=$(git rev-list --count refs/remotes/origin/develop..HEAD)
          IFS='/' read -ra strarr <<< "${GITHUB_REF#refs/heads/}"
          version="${strarr[1]}".$commits
          echo "::set-output name=version_name::$version"

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.release_version.outputs.version_name }}",
              sha: context.sha
            })

      - name: Generate release notes
        uses: RodrigoAmaroEng/release-notes-action@ab2df03c4cf0e0d7e34e28c35f704b3bec2a3c2e
        id: notes
        with:
          release_version: ${{ steps.release_version.outputs.version_name }}

      - name: Create a Release
        uses: actions/create-release@master
        with:
          tag_name: ${{ steps.library_version.outputs.version_name }}
          release_name: ${{ steps.library_version.outputs.version_name }}
          body: ${{ steps.notes.outputs.notes }}
